  {
    id: "bioderma-atoderm-intensive-baume",
    name: "Atoderm Intensive Baume",
    brand: "Bioderma",
    type: "body-care",
    score: "B",
    scoreNumeric: 83,
    subScores: { efficacy: "A", safety: "A", comedogenicity: "A", transparency: "B", skinTypeFit: "B" },
    price: 18,
    size: "500ml",
    country: "FR",
    concerns: ["acne", "dryness"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Paraffinum Liquidum", position: 3 },
      { name: "Helianthus Annuus Seed Oil", position: 4 },
      { name: "Behenyl Alcohol", position: 5 },
      { name: "Sucrose Stearate", position: 6 },
      { name: "Pentylene Glycol", position: 7 },
      { name: "Beta-Sitosterol", position: 8 },
      { name: "Xylitol", position: 9 },
      { name: "Zinc Gluconate", position: 10 },
      { name: "Palmitamide MEA", position: 11 },
      { name: "Sodium Citrate", position: 12 },
      { name: "Mannitol", position: 13 },
      { name: "Rhamnose", position: 14 },
      { name: "Sodium Lauroyl Lactylate", position: 15 },
      { name: "Sodium Hydroxide", position: 16 },
      { name: "Tocopherol", position: 17 },
      { name: "Phytosphingosine", position: 18 },
      { name: "Ceramide NP", position: 19 },
      { name: "Ethylhexylglycerin", position: 20 },
      { name: "Ceramide AP", position: 21 },
      { name: "Cholesterol", position: 22 },
      { name: "Carbomer", position: 23 },
      { name: "Xanthan Gum", position: 24 },
      { name: "Fructooligosaccharides", position: 25 },
      { name: "Caprylic/Capric Triglyceride", position: 26 },
      { name: "Laminaria Ochroleuca Extract", position: 27 },
      { name: "Citric Acid", position: 28 },
      { name: "Ceramide EOP", position: 29 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "nuxe-huile-prodigieuse",
    name: "Huile Prodigieuse",
    brand: "Nuxe",
    type: "body-care",
    score: "B",
    scoreNumeric: 77,
    subScores: { efficacy: "B", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 25,
    size: "100ml",
    country: "FR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Coco-Caprylate/Caprate", position: 1 },
      { name: "Macadamia Integrifolia Seed Oil", position: 2 },
      { name: "Dicaprylyl Ether", position: 3 },
      { name: "Caprylic/Capric Triglyceride", position: 4 },
      { name: "Prunus Amygdalus Dulcis Oil", position: 5 },
      { name: "Corylus Avellana Seed Oil", position: 6 },
      { name: "Camellia Oleifera Seed Oil", position: 7 },
      { name: "Parfum", position: 8 },
      { name: "Camellia Japonica Seed Oil", position: 9 },
      { name: "Tocopherol", position: 10 },
      { name: "Argania Spinosa Kernel Oil", position: 11 },
      { name: "Borago Officinalis Seed Oil", position: 12 },
      { name: "Tocopheryl Acetate", position: 13 },
      { name: "Helianthus Annuus Seed Oil", position: 14 },
      { name: "Rosmarinus Officinalis Leaf Extract", position: 15 },
      { name: "Ascorbic Acid", position: 16 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "caudalie-vinoperfect-radiance-serum",
    name: "Vinoperfect Radiance Serum",
    brand: "Caudalie",
    type: "serum",
    score: "B",
    scoreNumeric: 75,
    subScores: { efficacy: "B", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 40,
    size: "30ml",
    country: "FR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Butylene Glycol", position: 2 },
      { name: "Glycerin", position: 3 },
      { name: "Coco-Caprylate/Caprate", position: 4 },
      { name: "Squalane", position: 5 },
      { name: "Palmitoyl Grapevine Shoot Extract", position: 6 },
      { name: "Bisabolol", position: 7 },
      { name: "Glyceryl Stearate", position: 8 },
      { name: "Xanthan Gum", position: 9 },
      { name: "Caprylyl Glycol", position: 10 },
      { name: "Citric Acid", position: 11 },
      { name: "Sodium Phytate", position: 12 },
      { name: "Sodium Hydroxide", position: 13 },
      { name: "Parfum", position: 14 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "embryolisse-lait-creme-concentre",
    name: "Lait-Creme Concentre",
    brand: "Embryolisse",
    type: "moisturizer",
    score: "C",
    scoreNumeric: 63,
    subScores: { efficacy: "E", safety: "B", comedogenicity: "B", transparency: "C", skinTypeFit: "B" },
    price: 15,
    size: "75ml",
    country: "FR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Paraffinum Liquidum", position: 2 },
      { name: "Stearic Acid", position: 3 },
      { name: "Glyceryl Stearate", position: 4 },
      { name: "Triethanolamine", position: 5 },
      { name: "Cera Alba", position: 6 },
      { name: "Cetyl Palmitate", position: 7 },
      { name: "Butyrospermum Parkii Butter", position: 8 },
      { name: "Parfum", position: 9 },
      { name: "Steareth-10", position: 10 },
      { name: "Propylene Glycol", position: 11 },
      { name: "Aloe Barbadensis", position: 12 },
      { name: "Hydrolyzed Soy Protein", position: 13 },
      { name: "2-Hexanediol", position: 15 },
      { name: "Caprylyl Glycol", position: 16 },
      { name: "Polyacrylamide", position: 17 },
      { name: "C13-14 Isoparaffin", position: 18 },
      { name: "Laureth-7", position: 19 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "filorga-time-filler-cream",
    name: "Time-Filler Cream",
    brand: "Filorga",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 82,
    subScores: { efficacy: "A", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 55,
    size: "50ml",
    country: "FR",
    concerns: ["anti-aging", "acne", "dryness"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Butylene Glycol", position: 3 },
      { name: "Dicaprylyl Carbonate", position: 4 },
      { name: "Isododecane", position: 5 },
      { name: "Squalane", position: 6 },
      { name: "Dimethicone", position: 7 },
      { name: "Parfum", position: 8 },
      { name: "Phenoxyethanol", position: 9 },
      { name: "Sodium Hyaluronate", position: 10 },
      { name: "Niacinamide", position: 11 },
      { name: "Palmitoyl Tripeptide-38", position: 12 },
      { name: "Tocopherol", position: 13 },
      { name: "Ascorbic Acid", position: 14 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "uriage-eau-thermale-micellar-water",
    name: "Eau Thermale Micellar Water",
    brand: "Uriage",
    type: "cleanser",
    score: "B",
    scoreNumeric: 70,
    subScores: { efficacy: "C", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 11,
    size: "500ml",
    country: "FR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Polysorbate 20", position: 2 },
      { name: "Glycerin", position: 3 },
      { name: "Poloxamer 184", position: 4 },
      { name: "Caprylyl/Capryl Glucoside", position: 5 },
      { name: "Cetrimonium Bromide", position: 6 },
      { name: "Polyaminopropyl Biguanide", position: 7 },
      { name: "Parfum", position: 8 },
      { name: "Prunus Armeniaca Fruit Extract", position: 9 },
      { name: "Citric Acid", position: 10 },
      { name: "Ascorbic Acid", position: 11 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "svr-sensifine-ar-creme-spf50",
    name: "Sensifine AR Creme SPF50+",
    brand: "SVR",
    type: "sunscreen",
    score: "B",
    scoreNumeric: 76,
    subScores: { efficacy: "C", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 18,
    size: "40ml",
    country: "FR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Diethylamino Hydroxybenzoyl Hexyl Benzoate", position: 2 },
      { name: "Diisopropyl Adipate", position: 3 },
      { name: "Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine", position: 4 },
      { name: "Cetearyl Alcohol", position: 5 },
      { name: "Glycerin", position: 6 },
      { name: "Ethylhexyl Triazone", position: 7 },
      { name: "Silica", position: 8 },
      { name: "Dimethicone", position: 9 },
      { name: "Squalane", position: 10 },
      { name: "Tocopheryl Acetate", position: 11 },
      { name: "Caprylyl Glycol", position: 12 },
      { name: "Pentylene Glycol", position: 13 },
      { name: "Xanthan Gum", position: 14 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "ducray-keracnyl-pp-cream",
    name: "Keracnyl PP+ Cream",
    brand: "Ducray",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 78,
    subScores: { efficacy: "B", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 15,
    size: "30ml",
    country: "FR",
    concerns: ["acne", "dryness"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Caprylic/Capric Triglyceride", position: 2 },
      { name: "Cetearyl Alcohol", position: 3 },
      { name: "Niacinamide", position: 4 },
      { name: "Pentylene Glycol", position: 5 },
      { name: "Butylene Glycol", position: 6 },
      { name: "Glycerin", position: 7 },
      { name: "Butyrospermum Parkii Butter", position: 8 },
      { name: "Cetearyl Glucoside", position: 9 },
      { name: "Glyceryl Laurate", position: 10 },
      { name: "Myrtus Communis Leaf Extract", position: 11 },
      { name: "Sodium Hydroxide", position: 12 },
      { name: "Tocopherol", position: 13 },
      { name: "Xanthan Gum", position: 14 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "a-derma-exomega-control-cream",
    name: "Exomega Control Cream",
    brand: "A-Derma",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 79,
    subScores: { efficacy: "B", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 15,
    size: "200ml",
    country: "FR",
    concerns: ["acne", "dryness"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Caprylic/Capric Triglyceride", position: 2 },
      { name: "Glycerin", position: 3 },
      { name: "Cetearyl Alcohol", position: 4 },
      { name: "Niacinamide", position: 5 },
      { name: "Avena Sativa Leaf/Stem Extract", position: 6 },
      { name: "Caprylyl Glycol", position: 7 },
      { name: "Cetearyl Glucoside", position: 8 },
      { name: "Cetyl Alcohol", position: 9 },
      { name: "Glyceryl Stearate", position: 10 },
      { name: "Oenothera Biennis Oil", position: 11 },
      { name: "Sodium Hydroxide", position: 12 },
      { name: "Tocopherol", position: 13 },
      { name: "Tocopheryl Acetate", position: 14 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "mustela-stelatopia-emollient-cream",
    name: "Stelatopia Emollient Cream",
    brand: "Mustela",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 78,
    subScores: { efficacy: "B", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 15,
    size: "200ml",
    country: "FR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Petrolatum", position: 3 },
      { name: "Caprylic/Capric Triglyceride", position: 4 },
      { name: "Helianthus Annuus Seed Oil Unsaponifiables", position: 5 },
      { name: "Squalane", position: 6 },
      { name: "Xanthan Gum", position: 7 },
      { name: "Persea Gratissima Fruit Extract", position: 8 },
      { name: "Ceramide NP", position: 9 },
      { name: "Phytosphingosine", position: 10 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "bioderma-sebium-global",
    name: "Sebium Global",
    brand: "Bioderma",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 76,
    subScores: { efficacy: "B", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 17,
    size: "30ml",
    country: "FR",
    concerns: ["acne", "dryness"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Zinc Gluconate", position: 3 },
      { name: "Salicylic Acid", position: 4 },
      { name: "Mannitol", position: 5 },
      { name: "Xylitol", position: 6 },
      { name: "Rhamnose", position: 7 },
      { name: "Fructooligosaccharides", position: 8 },
      { name: "Laminaria Ochroleuca Extract", position: 9 },
      { name: "Ginkgo Biloba Leaf Extract", position: 10 },
      { name: "Bakuchiol", position: 11 },
      { name: "Squalane", position: 12 },
      { name: "Parfum", position: 13 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "avene-cleanance-comedomed",
    name: "Cleanance Comedomed",
    brand: "Avene",
    type: "serum",
    score: "C",
    scoreNumeric: 65,
    subScores: { efficacy: "E", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 18,
    size: "30ml",
    country: "FR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Isopropyl Alcohol", position: 2 },
      { name: "PEG-6", position: 3 },
      { name: "Glycerin", position: 4 },
      { name: "Silybum Marianum Fruit Extract", position: 5 },
      { name: "Silica", position: 6 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "la-roche-posay-hyalu-b5-serum",
    name: "Hyalu B5 Serum",
    brand: "La Roche-Posay",
    type: "serum",
    score: "B",
    scoreNumeric: 78,
    subScores: { efficacy: "A", safety: "C", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 35,
    size: "30ml",
    country: "FR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Alcohol Denat", position: 3 },
      { name: "Propylene Glycol", position: 4 },
      { name: "Panthenol", position: 5 },
      { name: "Pentylene Glycol", position: 6 },
      { name: "Dimethicone", position: 7 },
      { name: "Sodium Hyaluronate", position: 8 },
      { name: "Hydrolyzed Hyaluronic Acid", position: 9 },
      { name: "Caprylyl Glycol", position: 10 },
      { name: "Citric Acid", position: 11 },
      { name: "Xanthan Gum", position: 12 },
      { name: "Butylene Glycol", position: 13 },
      { name: "Tocopherol", position: 14 },
      { name: "Phenoxyethanol", position: 15 },
      { name: "Parfum", position: 16 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "vichy-liftactiv-collagen-specialist",
    name: "Liftactiv Collagen Specialist",
    brand: "Vichy",
    type: "moisturizer",
    score: "C",
    scoreNumeric: 65,
    subScores: { efficacy: "C", safety: "C", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 35,
    size: "50ml",
    country: "FR",
    concerns: ["anti-aging", "dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Dimethicone", position: 3 },
      { name: "Isohexadecane", position: 4 },
      { name: "Alcohol Denat", position: 5 },
      { name: "Silica", position: 6 },
      { name: "Propanediol", position: 7 },
      { name: "Adenosine", position: 8 },
      { name: "Ascorbyl Glucoside", position: 9 },
      { name: "Nylon-12", position: 10 },
      { name: "Tocopherol", position: 11 },
      { name: "Phenoxyethanol", position: 12 },
      { name: "Parfum", position: 13 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "caudalie-vinosource-hydra-sos-cream",
    name: "Vinosource-Hydra SOS Cream",
    brand: "Caudalie",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 81,
    subScores: { efficacy: "A", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 26,
    size: "50ml",
    country: "FR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Ethylhexyl Cocoate", position: 3 },
      { name: "Squalane", position: 4 },
      { name: "Cetearyl Alcohol", position: 5 },
      { name: "Vitis Vinifera Fruit Water", position: 6 },
      { name: "Borago Officinalis Seed Oil", position: 7 },
      { name: "Caprylic/Capric Triglyceride", position: 8 },
      { name: "Tocopheryl Acetate", position: 9 },
      { name: "Carbomer", position: 10 },
      { name: "Caprylyl Glycol", position: 11 },
      { name: "Tocopherol", position: 12 },
      { name: "Helianthus Annuus Seed Oil", position: 13 },
      { name: "Sodium Hyaluronate", position: 14 },
      { name: "Parfum", position: 15 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "nuxe-creme-fraiche-de-beaute",
    name: "Creme Fraiche de Beaute",
    brand: "Nuxe",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 73,
    subScores: { efficacy: "C", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 21,
    size: "50ml",
    country: "FR",
    concerns: ["dryness", "sensitivity"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Caprylic/Capric Triglyceride", position: 3 },
      { name: "Dicaprylyl Ether", position: 4 },
      { name: "Butyrospermum Parkii Butter", position: 5 },
      { name: "Cetearyl Alcohol", position: 6 },
      { name: "Macadamia Integrifolia Seed Oil", position: 7 },
      { name: "Parfum", position: 8 },
      { name: "Dimethicone", position: 9 },
      { name: "Tocopherol", position: 10 },
      { name: "Phenoxyethanol", position: 11 },
      { name: "Ethylhexylglycerin", position: 12 },
      { name: "Allantoin", position: 13 },
      { name: "Camellia Oleifera Seed Oil", position: 14 },
      { name: "Camellia Sinensis Leaf Extract", position: 15 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "svr-ampoule-b3-niacinamide",
    name: "Ampoule B3 Niacinamide",
    brand: "SVR",
    type: "serum",
    score: "A",
    scoreNumeric: 86,
    subScores: { efficacy: "A", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 25,
    size: "30ml",
    country: "FR",
    concerns: ["acne", "dryness"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Niacinamide", position: 3 },
      { name: "Isopentyldiol", position: 4 },
      { name: "Sodium Hyaluronate Crosspolymer", position: 5 },
      { name: "Hydrolyzed Hyaluronic Acid", position: 6 },
      { name: "Sodium Hyaluronate", position: 7 },
      { name: "2-Hexanediol", position: 9 },
      { name: "Caprylyl Glycol", position: 10 },
      { name: "Pentylene Glycol", position: 11 },
      { name: "Sodium Hydroxide", position: 12 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "topicrem-da-emollient-balm",
    name: "DA Emollient Balm",
    brand: "Topicrem",
    type: "body-care",
    score: "B",
    scoreNumeric: 78,
    subScores: { efficacy: "B", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 15,
    size: "500ml",
    country: "FR",
    concerns: ["dryness", "sensitivity"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Paraffinum Liquidum", position: 2 },
      { name: "Glycerin", position: 3 },
      { name: "Butyrospermum Parkii Butter", position: 4 },
      { name: "Linum Usitatissimum Seed Oil", position: 5 },
      { name: "Allantoin", position: 6 },
      { name: "Carbomer", position: 7 },
      { name: "Tocopherol", position: 8 },
      { name: "Sodium Hydroxide", position: 9 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "cerave-sa-smoothing-cleanser",
    name: "SA Smoothing Cleanser",
    brand: "CeraVe",
    type: "cleanser",
    score: "A",
    scoreNumeric: 86,
    subScores: { efficacy: "A", safety: "B", comedogenicity: "A", transparency: "B", skinTypeFit: "B" },
    price: 12,
    size: "236ml",
    country: "US",
    concerns: ["acne", "dryness"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Sodium Lauroyl Sarcosinate", position: 2 },
      { name: "Cocamidopropyl Hydroxysultaine", position: 3 },
      { name: "Glycerin", position: 4 },
      { name: "Niacinamide", position: 5 },
      { name: "Ceramide NP", position: 6 },
      { name: "Ceramide AP", position: 7 },
      { name: "Ceramide EOP", position: 8 },
      { name: "Carbomer", position: 9 },
      { name: "Salicylic Acid", position: 10 },
      { name: "Sodium Benzoate", position: 11 },
      { name: "Sodium Lauroyl Lactylate", position: 12 },
      { name: "Cholesterol", position: 13 },
      { name: "Phenoxyethanol", position: 14 },
      { name: "Hydrolyzed Hyaluronic Acid", position: 15 },
      { name: "Phytosphingosine", position: 16 },
      { name: "Xanthan Gum", position: 17 },
      { name: "Ethylhexylglycerin", position: 18 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "tatcha-the-dewy-skin-cream",
    name: "The Dewy Skin Cream",
    brand: "Tatcha",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 72,
    subScores: { efficacy: "B", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 68,
    size: "50ml",
    country: "JP",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Propanediol", position: 3 },
      { name: "Dimethicone", position: 4 },
      { name: "Squalane", position: 5 },
      { name: "Diisostearyl Malate", position: 6 },
      { name: "Behenyl Alcohol", position: 7 },
      { name: "Sodium Hyaluronate", position: 8 },
      { name: "Inositol", position: 9 },
      { name: "Sericin", position: 10 },
      { name: "Butylene Glycol", position: 11 },
      { name: "Ethylhexylglycerin", position: 12 },
      { name: "Parfum", position: 13 },
      { name: "Phenoxyethanol", position: 14 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "drunk-elephant-t-l-c-framboos-glycolic-night-serum",
    name: "T.L.C. Framboos Glycolic Night Serum",
    brand: "Drunk Elephant",
    type: "serum",
    score: "A",
    scoreNumeric: 86,
    subScores: { efficacy: "A", safety: "B", comedogenicity: "A", transparency: "B", skinTypeFit: "B" },
    price: 87,
    size: "50ml",
    country: "US",
    concerns: ["acne", "dryness", "sensitivity"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycolic Acid", position: 2 },
      { name: "Butylene Glycol", position: 3 },
      { name: "Glycerin", position: 4 },
      { name: "Sodium Hydroxide", position: 5 },
      { name: "Salicylic Acid", position: 6 },
      { name: "Lactic Acid", position: 7 },
      { name: "Citric Acid", position: 8 },
      { name: "Aloe Barbadensis Leaf Juice", position: 9 },
      { name: "Camellia Sinensis Leaf Extract", position: 10 },
      { name: "Rubus Idaeus Fruit Extract", position: 11 },
      { name: "Sclerocarya Birrea Seed Oil", position: 12 },
      { name: "Sodium Hyaluronate Crosspolymer", position: 13 },
      { name: "Allantoin", position: 14 },
      { name: "Propanediol", position: 15 },
      { name: "Phenoxyethanol", position: 16 },
      { name: "Caprylyl Glycol", position: 17 },
      { name: "Ethylhexylglycerin", position: 18 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "sunday-riley-good-genes-all-in-one-lactic-acid-treatment",
    name: "Good Genes All-in-One Lactic Acid Treatment",
    brand: "Sunday Riley",
    type: "serum",
    score: "B",
    scoreNumeric: 80,
    subScores: { efficacy: "B", safety: "B", comedogenicity: "B", transparency: "B", skinTypeFit: "B" },
    price: 85,
    size: "30ml",
    country: "US",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Caprylic/Capric Triglyceride", position: 2 },
      { name: "Squalane", position: 3 },
      { name: "Lactic Acid", position: 4 },
      { name: "Propanediol", position: 5 },
      { name: "Butylene Glycol", position: 6 },
      { name: "Stearic Acid", position: 7 },
      { name: "Dimethicone", position: 8 },
      { name: "Cetearyl Alcohol", position: 9 },
      { name: "Glyceryl Stearate", position: 10 },
      { name: "Glycyrrhiza Glabra Root Extract", position: 11 },
      { name: "Phenoxyethanol", position: 12 },
      { name: "Xanthan Gum", position: 13 },
      { name: "Caprylyl Glycol", position: 14 },
      { name: "Chlorphenesin", position: 15 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "glow-recipe-watermelon-glow-niacinamide-dew-drops",
    name: "Watermelon Glow Niacinamide Dew Drops",
    brand: "Glow Recipe",
    type: "serum",
    score: "B",
    scoreNumeric: 75,
    subScores: { efficacy: "B", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 34,
    size: "40ml",
    country: "US",
    concerns: ["acne", "dryness"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Propanediol", position: 2 },
      { name: "Glycerin", position: 3 },
      { name: "Niacinamide", position: 4 },
      { name: "Citrullus Lanatus Fruit Extract", position: 5 },
      { name: "Sodium Hyaluronate", position: 6 },
      { name: "Cetearyl Alcohol", position: 7 },
      { name: "Carbomer", position: 8 },
      { name: "Ethylhexylglycerin", position: 9 },
      { name: "Xanthan Gum", position: 10 },
      { name: "Moringa Oleifera Seed Oil", position: 11 },
      { name: "Fragrance", position: 12 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "supergoop-unseen-sunscreen-spf40",
    name: "Unseen Sunscreen SPF40",
    brand: "Supergoop",
    type: "sunscreen",
    score: "B",
    scoreNumeric: 72,
    subScores: { efficacy: "C", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 35,
    size: "50ml",
    country: "US",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Avobenzone", position: 1 },
      { name: "Homosalate", position: 2 },
      { name: "Octisalate", position: 3 },
      { name: "Octocrylene", position: 4 },
      { name: "Isododecane", position: 5 },
      { name: "Dimethicone Crosspolymer", position: 6 },
      { name: "Caprylic/Capric Triglyceride", position: 7 },
      { name: "Butyrospermum Parkii Butter", position: 8 },
      { name: "Jojoba Esters", position: 9 },
      { name: "Silica", position: 10 },
      { name: "Tocopherol", position: 11 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "first-aid-beauty-ultra-repair-cream",
    name: "Ultra Repair Cream",
    brand: "First Aid Beauty",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 84,
    subScores: { efficacy: "A", safety: "B", comedogenicity: "B", transparency: "B", skinTypeFit: "B" },
    price: 33,
    size: "170g",
    country: "US",
    concerns: ["dryness", "sensitivity"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Stearic Acid", position: 2 },
      { name: "Glycerin", position: 3 },
      { name: "C12-15 Alkyl Benzoate", position: 4 },
      { name: "Caprylic/Capric Triglyceride", position: 5 },
      { name: "Cetearyl Alcohol", position: 6 },
      { name: "Colloidal Oatmeal", position: 7 },
      { name: "Squalane", position: 8 },
      { name: "Ceramide NP", position: 9 },
      { name: "Allantoin", position: 10 },
      { name: "Camellia Sinensis Leaf Extract", position: 11 },
      { name: "Glycyrrhiza Glabra Root Extract", position: 12 },
      { name: "Butyrospermum Parkii Butter", position: 13 },
      { name: "Dimethicone", position: 14 },
      { name: "Caprylyl Glycol", position: 15 },
      { name: "Xanthan Gum", position: 16 },
      { name: "Phenoxyethanol", position: 17 },
      { name: "Sodium Hydroxide", position: 18 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "youth-to-the-people-superfood-cleanser",
    name: "Superfood Cleanser",
    brand: "Youth to the People",
    type: "cleanser",
    score: "B",
    scoreNumeric: 80,
    subScores: { efficacy: "B", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 36,
    size: "237ml",
    country: "US",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Sodium Cocoyl Glutamate", position: 2 },
      { name: "Cocamidopropyl Betaine", position: 3 },
      { name: "Panthenol", position: 4 },
      { name: "Tocopheryl Acetate", position: 5 },
      { name: "Ascorbic Acid", position: 6 },
      { name: "Butylene Glycol", position: 7 },
      { name: "Brassica Oleracea Leaf Extract", position: 8 },
      { name: "Spinacia Oleracea Leaf Extract", position: 9 },
      { name: "Camellia Sinensis Leaf Extract", position: 10 },
      { name: "Aloe Barbadensis Leaf Extract", position: 11 },
      { name: "Phenoxyethanol", position: 12 },
      { name: "Glycerin", position: 13 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "laneige-water-sleeping-mask",
    name: "Water Sleeping Mask",
    brand: "Laneige",
    type: "mask",
    score: "C",
    scoreNumeric: 68,
    subScores: { efficacy: "C", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 30,
    size: "70ml",
    country: "KR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Butylene Glycol", position: 2 },
      { name: "Cyclopentasiloxane", position: 3 },
      { name: "Glycerin", position: 4 },
      { name: "Trehalose", position: 5 },
      { name: "Sodium Hyaluronate", position: 6 },
      { name: "Beta-Glucan", position: 7 },
      { name: "Ascorbyl Glucoside", position: 8 },
      { name: "Dimethicone", position: 9 },
      { name: "Propanediol", position: 10 },
      { name: "Ethylhexylglycerin", position: 11 },
      { name: "Carbomer", position: 12 },
      { name: "Phenoxyethanol", position: 13 },
      { name: "Fragrance", position: 14 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "innisfree-green-tea-seed-serum",
    name: "Green Tea Seed Serum",
    brand: "Innisfree",
    type: "serum",
    score: "B",
    scoreNumeric: 70,
    subScores: { efficacy: "C", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 24,
    size: "80ml",
    country: "KR",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Propanediol", position: 2 },
      { name: "Alcohol", position: 3 },
      { name: "Glycerin", position: 4 },
      { name: "Betaine", position: 5 },
      { name: "Camellia Sinensis Seed Oil", position: 6 },
      { name: "Panthenol", position: 7 },
      { name: "Ethylhexylglycerin", position: 8 },
      { name: "Camellia Sinensis Leaf Extract", position: 9 },
      { name: "Fragrance", position: 10 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "summer-fridays-jet-lag-mask",
    name: "Jet Lag Mask",
    brand: "Summer Fridays",
    type: "mask",
    score: "A",
    scoreNumeric: 86,
    subScores: { efficacy: "A", safety: "B", comedogenicity: "A", transparency: "B", skinTypeFit: "B" },
    price: 48,
    size: "64g",
    country: "US",
    concerns: ["acne", "dryness"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Caprylic/Capric Triglyceride", position: 2 },
      { name: "Pentylene Glycol", position: 3 },
      { name: "Butyrospermum Parkii Butter", position: 4 },
      { name: "Cetearyl Alcohol", position: 5 },
      { name: "Niacinamide", position: 6 },
      { name: "Glycerin", position: 7 },
      { name: "Ceramide NP", position: 8 },
      { name: "Ceramide EOP", position: 9 },
      { name: "Ceramide AP", position: 10 },
      { name: "Phytosphingosine", position: 11 },
      { name: "Cholesterol", position: 12 },
      { name: "Sodium Lauroyl Lactylate", position: 13 },
      { name: "Sodium Hyaluronate", position: 14 },
      { name: "Carbomer", position: 15 },
      { name: "Xanthan Gum", position: 16 },
      { name: "Phenoxyethanol", position: 17 },
      { name: "Ethylhexylglycerin", position: 18 },
      { name: "Tocopheryl Acetate", position: 19 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "versed-dew-point-moisturizing-gel-cream",
    name: "Dew Point Moisturizing Gel-Cream",
    brand: "Versed",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 76,
    subScores: { efficacy: "C", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 17,
    size: "60ml",
    country: "US",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Propylene Glycol", position: 3 },
      { name: "Squalane", position: 4 },
      { name: "Aloe Barbadensis Leaf Juice", position: 5 },
      { name: "Camellia Sinensis Leaf Extract", position: 6 },
      { name: "Simmondsia Chinensis Seed Oil", position: 7 },
      { name: "Phenoxyethanol", position: 8 },
      { name: "Carbomer", position: 9 },
      { name: "Sodium Hydroxide", position: 10 },
      { name: "Sodium Hyaluronate", position: 11 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "good-molecules-discoloration-correcting-serum",
    name: "Discoloration Correcting Serum",
    brand: "Good Molecules",
    type: "serum",
    score: "B",
    scoreNumeric: 74,
    subScores: { efficacy: "C", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 10,
    size: "30ml",
    country: "US",
    concerns: ["acne", "dryness"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Propanediol", position: 2 },
      { name: "Glycerin", position: 3 },
      { name: "Niacinamide", position: 4 },
      { name: "Cetyl Tranexamate Mesylate", position: 5 },
      { name: "Cetearyl Alcohol", position: 6 },
      { name: "Caprylyl Glycol", position: 7 },
      { name: "Ethylhexylglycerin", position: 8 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "the-inkey-list-retinol-serum",
    name: "Retinol Serum",
    brand: "The Inkey List",
    type: "serum",
    score: "A",
    scoreNumeric: 85,
    subScores: { efficacy: "A", safety: "B", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 10,
    size: "30ml",
    country: "GB",
    concerns: ["anti-aging", "dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Glycerin", position: 2 },
      { name: "Butylene Glycol", position: 3 },
      { name: "Propanediol", position: 4 },
      { name: "Dicaprylyl Carbonate", position: 5 },
      { name: "Dimethicone", position: 6 },
      { name: "Squalane", position: 7 },
      { name: "Dimethyl Isosorbide", position: 8 },
      { name: "Tocopherol", position: 9 },
      { name: "Retinol", position: 10 },
      { name: "Hyaluronic Acid", position: 11 },
      { name: "Palmitoyl Tetrapeptide-7", position: 12 },
      { name: "Palmitoyl Tripeptide-1", position: 13 },
      { name: "Phenoxyethanol", position: 14 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "dermalogica-daily-microfoliant",
    name: "Daily Microfoliant",
    brand: "Dermalogica",
    type: "exfoliant",
    score: "B",
    scoreNumeric: 81,
    subScores: { efficacy: "B", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 62,
    size: "74g",
    country: "US",
    concerns: ["acne", "sensitivity"],
    bestFor: ["dry", "sensitive", "combination", "normal", "oily"],
    ingredients: [
      { name: "Oryza Sativa Bran", position: 1 },
      { name: "Oryza Sativa Starch", position: 2 },
      { name: "Allantoin", position: 3 },
      { name: "Papain", position: 4 },
      { name: "Salicylic Acid", position: 5 },
      { name: "Ginkgo Biloba Leaf Extract", position: 6 },
      { name: "Camellia Sinensis Leaf Extract", position: 7 },
      { name: "Glycyrrhiza Glabra Root Extract", position: 8 },
      { name: "Melaleuca Alternifolia Leaf Oil", position: 9 },
      { name: "Citric Acid", position: 10 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "eltamd-uv-clear-spf46",
    name: "UV Clear SPF46",
    brand: "EltaMD",
    type: "sunscreen",
    score: "B",
    scoreNumeric: 79,
    subScores: { efficacy: "A", safety: "C", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 37,
    size: "48g",
    country: "US",
    concerns: ["acne"],
    bestFor: ["normal", "oily", "combination"],
    ingredients: [
      { name: "Zinc Oxide", position: 1 },
      { name: "Octinoxate", position: 2 },
      { name: "Niacinamide", position: 3 },
      { name: "Sodium Hyaluronate", position: 4 },
      { name: "Tocopheryl Acetate", position: 5 },
      { name: "Lactic Acid", position: 6 },
      { name: "Phenoxyethanol", position: 7 },
      { name: "Butylene Glycol", position: 8 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "tower-28-sos-daily-rescue-facial-spray",
    name: "SOS Daily Rescue Facial Spray",
    brand: "Tower 28",
    type: "toner",
    score: "C",
    scoreNumeric: 63,
    subScores: { efficacy: "E", safety: "A", comedogenicity: "A", transparency: "D", skinTypeFit: "B" },
    price: 28,
    size: "120ml",
    country: "US",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Electrolyzed Water", position: 1 },
      { name: "Sodium Chloride", position: 2 },
      { name: "Hypochlorous Acid", position: 3 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "farmacy-green-clean-makeup-meltaway-balm",
    name: "Green Clean Makeup Meltaway Balm",
    brand: "Farmacy",
    type: "cleanser",
    score: "B",
    scoreNumeric: 73,
    subScores: { efficacy: "C", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 34,
    size: "100ml",
    country: "US",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Cetyl Ethylhexanoate", position: 1 },
      { name: "Caprylic/Capric Triglyceride", position: 2 },
      { name: "Phenoxyethanol", position: 3 },
      { name: "Moringa Oleifera Seed Oil", position: 4 },
      { name: "Echinacea Purpurea Root Extract", position: 5 },
      { name: "Helianthus Annuus Seed Oil", position: 6 },
      { name: "Glycerin", position: 7 },
      { name: "Butylene Glycol", position: 8 },
      { name: "Citric Acid", position: 9 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "cocokind-texture-smoothing-cream",
    name: "Texture Smoothing Cream",
    brand: "Cocokind",
    type: "moisturizer",
    score: "B",
    scoreNumeric: 73,
    subScores: { efficacy: "C", safety: "A", comedogenicity: "B", transparency: "C", skinTypeFit: "B" },
    price: 17,
    size: "50ml",
    country: "US",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aqua", position: 1 },
      { name: "Squalane", position: 2 },
      { name: "Caprylic/Capric Triglyceride", position: 3 },
      { name: "Helianthus Annuus Seed Oil", position: 4 },
      { name: "Cetyl Alcohol", position: 5 },
      { name: "Glyceryl Stearate", position: 6 },
      { name: "Butyrospermum Parkii Butter", position: 7 },
      { name: "Glycerin", position: 8 },
      { name: "Camellia Japonica Seed Oil", position: 9 },
      { name: "Panax Ginseng Root Extract", position: 10 },
      { name: "Xanthan Gum", position: 11 },
      { name: "Stearic Acid", position: 12 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },
  {
    id: "herbivore-prism-glow-potion",
    name: "Prism Glow Potion",
    brand: "Herbivore",
    type: "exfoliant",
    score: "B",
    scoreNumeric: 74,
    subScores: { efficacy: "C", safety: "A", comedogenicity: "A", transparency: "C", skinTypeFit: "B" },
    price: 53,
    size: "30ml",
    country: "US",
    concerns: ["dryness"],
    bestFor: ["normal", "dry", "sensitive"],
    ingredients: [
      { name: "Aloe Barbadensis Leaf Juice", position: 1 },
      { name: "Sodium Hyaluronate", position: 2 },
      { name: "Rosa Damascena Flower Water", position: 3 },
      { name: "Glycerin", position: 4 },
      { name: "Salix Nigra Bark Extract", position: 5 },
      { name: "Terminalia Ferdinandiana Fruit Extract", position: 6 },
      { name: "Vaccinium Myrtillus Extract", position: 7 },
      { name: "Citrus Aurantium Dulcis Fruit Extract", position: 8 },
      { name: "Citrus Limon Fruit Extract", position: 9 },
      { name: "Hibiscus Sabdariffa Flower Extract", position: 10 },
    ],
    summary: { en: "", fr: "" },
    strengths: { en: [], fr: [] },
    weaknesses: { en: [], fr: [] },
    claims: {},
    tags: [],
  },